INSERT INTO quizzes (owner_id, title, description, is_public)
VALUES
(1, 'General Knowledge 101', 'A basic quiz on various topics.', TRUE),
(2, 'Movie Trivia', 'Test your knowledge of classic films.', TRUE),
(3, 'Science Quiz', 'Questions about physics, chemistry, and biology.', FALSE),
(4, 'Pop Music Quiz', "From oldies to today's hits.", TRUE),
(5, 'History of the World', 'A comprehensive history quiz.', FALSE),
(6, 'Art and Literature', 'Test your artsy side!', TRUE),
(7, 'Sports Fan Quiz', 'For the ultimate sports enthusiast.', TRUE),
(8, 'Coding Challenge', 'A quiz for programmers.', FALSE),
(9, 'Geography Quiz', 'Where in the world?', TRUE),
(10, 'Food and Cooking', 'Test your culinary skills.', FALSE),
(11, 'Video Game Trivia', 'For all gamers out there.', TRUE),
(12, 'Mythology Quiz', 'Greek and Roman myths.', TRUE),
(13, 'Animal Kingdom', 'A quiz about the animal world.', FALSE),
(14, 'Space Exploration', 'Journey to the stars.', TRUE),
(15, 'Famous Quotes', 'Who said that?', TRUE),
(16, 'Fashion and Style', 'Test your fashion sense.', FALSE),
(17, 'Car Enthusiast Quiz', 'For all car lovers.', TRUE),
(18, 'The Office Trivia', 'Test your knowledge of Dunder Mifflin.', TRUE),
(19, 'Natural Wonders', 'Explore the beauty of nature.', FALSE),
(20, 'Board Game Quiz', 'For board game aficionados.', TRUE),
(21, 'Comic Book Quiz', 'Superheroes and villains.', TRUE),
(22, 'Travel Destinations', 'Explore the world.', FALSE),
(23, 'Music Theory', 'For the musically inclined.', TRUE),
(24, 'Classic Literature', 'Test your reading skills.', TRUE),
(25, 'Math Puzzles', 'Solve the equations.', FALSE);
