INSERT INTO questions (quiz_id, question_text)
VALUES
(1, 'What is the capital of France?'),
(1, 'Which planet is known as the Red Planet?'),
(1, 'What is the largest ocean in the world?'),
(1, 'Who painted the Mona Lisa?'),
(2, 'In which year was the first Star Wars movie released?'),
(2, 'Who directed the movie "The Godfather"?'),
(2, 'Which actor played Jack in "Titanic"?'),
(2, 'What is the highest-grossing film of all time? (Unadjusted for inflation)'),
(3, 'What is the chemical symbol for water?'),
(3, 'What is the powerhouse of the cell?'),
(3, 'What is the speed of light?'),
(3, 'What is the atomic number of oxygen?'),
(4, 'Who sang "Bohemian Rhapsody"?'),
(4, 'Which artist released the album "Thriller"?'),
(4, 'What year was "Like a Prayer" by Madonna released?'),
(4, 'Who is known as the King of Pop?'),
(5, 'In which year did World War I begin?'),
(5, 'Who was the first president of the United States?'),
(5, 'What ancient civilization built the pyramids of Giza?'),
(5, 'What was the name of the ship that sank in 1912?'),
(6, 'Who wrote "Romeo and Juliet"?'),
(6, 'Which artist painted "Starry Night"?'),
(6, 'What is the name of the famous sculpture by Michelangelo?'),
(6, 'What is the name of the famous impressionist painter who painted water lilies?'),
(7, 'Which team has won the most Super Bowl titles?'),
(7, 'Who holds the record for most Olympic gold medals?'),
(7, 'Which country won the FIFA World Cup in 2018?'),
(7, 'Who is considered the greatest basketball player of all time?'),
(8, 'What is the output of "print(2 + 2)" in Python?'),
(8, 'What does HTML stand for?'),
(8, 'What is a loop in programming?'),
(8, 'What is the difference between a list and a tuple in Python?'),
(9, 'Which continent is the largest?'),
(9, 'What is the longest river in the world?'),
(9, 'Which country is known as the Land of the Rising Sun?'),
(9, 'What is the capital of Australia?'),
(10, 'What is the main ingredient in guacamole?'),
(10, 'Which country is famous for pizza?'),
(10, 'What is the name of the Japanese dish made with raw fish?'),
(10, 'What spice gives curry its yellow color?'),
(11, 'Which video game features the character Mario?'),
(11, 'What is the name of the main character in the Legend of Zelda series?'),
(11, 'What is the best selling video game of all time?'),
(11, 'In which game does the player build structures with blocks?'),
(12, 'Who is the Greek god of the sea?'),
(12, 'What is the name of the Norse god of thunder?'),
(12, 'Who was the Roman god of war?'),
(12, 'What creature has the head of a lion and the body of a bird?'),
(13, 'Which animal is known as the king of the jungle?'),
(13, 'What is the largest mammal in the world?'),
(13, 'Which bird is known for its ability to mimic human speech?'),
(13, 'What is the fastest land animal?'),
(14, 'Who was the first person to walk on the moon?'),
(14, 'What is the name of the largest planet in our solar system?'),
(14, 'Which planet is known for its rings?'),
(14, 'What is the name of our galaxy?'),
(15, 'Who said, "To be or not to be, that is the question"?'),
(15, 'Who said, "I have a dream"?'),
(15, 'Who said, "The only thing we have to fear is fear itself"?'),
(15, 'Who said, "Ask not what your country can do for you..."?'),
(16, 'What is the term for a piece of clothing worn around the neck?'),
(16, 'Which fashion designer created the "little black dress"?'),
(16, 'What is the name of the material made from sheep''s wool?'),
(16, 'What is the name of a shoe with a high heel?'),
(17, 'Which car brand is known for its luxury SUVs?'),
(17, 'What is the name of the first mass-produced automobile?'),
(17, 'What is the term for a car with a retractable roof?'),
(17, 'What is the name of the Italian sports car brand with a prancing horse logo?'),
(18, 'What is the name of Michael Scott''s favorite paper company?'),
(18, 'Who does Jim Halpert marry?'),
(18, 'What is Dwight Schrute''s profession?'),
(18, 'What is the name of the annual award show hosted by Dunder Mifflin?'),
(19, 'What is the name of the largest waterfall in the world?'),
(19, 'Which mountain range is the longest in the world?'),
(19, 'What is the name of the largest desert in the world?'),
(19, 'What is the name of the deepest point in the ocean?'),
(20, 'What is the name of the board game where you buy properties?'),
(20, 'Which board game involves solving a murder mystery?'),
(20, 'What is the name of the strategy board game with pieces like "Risk"?'),
(20, 'What board game is played on a 64 square board?'),
(21, 'Who is the creator of Batman?'),
(21, 'What is the name of Superman''s alter ego?'),
(21, 'Which comic book company created Spider-Man?'),
(21, 'What is the name of the villain from the comic book, Watchmen?'),
(22, 'Which city is known as the "Eternal City"?'),
(22, 'What is the name of the famous tower in Paris?'),
(22, 'Which country is home to the Great Barrier Reef?'),
(22, 'What is the name of the ancient city located in Peru?'),
(23, 'What is the term for a series of musical notes arranged in a definite pattern of pitch?'),
(23, 'What is the term for the speed of the music?'),
(23, 'What is the term for the loudness or softness of a musical sound?'),
(23, 'What is the name of the musical symbol that raises a note by a half step?'),
(24, 'Who wrote "Pride and Prejudice"?'),
(24, 'What is the name of the protagonist in "To Kill a Mockingbird"?'),
(24, 'What is the name of the famous play by Tennessee Williams?'),
(24, 'Who wrote "The Great Gatsby"?'),
(25, 'What is the value of pi?'),
(25, 'What is the square root of 144?'),
(25, 'Solve for x: 2x + 5 = 11'),
(25, 'What is the next number in the sequence: 2, 4, 8, 16, ?');
