INSERT INTO answers (question_id, answer_text, is_correct)
VALUES
(1, 'London', FALSE),
(1, 'Paris', TRUE),
(1, 'Berlin', FALSE),
(1, 'Madrid', FALSE),
(2, 'Venus', FALSE),
(2, 'Mars', TRUE),
(2, 'Jupiter', FALSE),
(2, 'Saturn', FALSE),
(3, 'Atlantic Ocean', FALSE),
(3, 'Indian Ocean', FALSE),
(3, 'Pacific Ocean', TRUE),
(3, 'Arctic Ocean', FALSE),
(4, 'Vincent van Gogh', FALSE),
(4, 'Leonardo da Vinci', TRUE),
(4, 'Michelangelo', FALSE),
(4, 'Raphael', FALSE),
(5, '1977', TRUE),
(5, '1980', FALSE),
(5, '1975', FALSE),
(5, '1983', FALSE),
(6, 'Steven Spielberg', FALSE),
(6, 'Francis Ford Coppola', TRUE),
(6, 'Martin Scorsese', FALSE),
(6, 'Christopher Nolan', FALSE),
(7, 'Leonardo DiCaprio', TRUE),
(7, 'Brad Pitt', FALSE),
(7, 'Tom Hanks', FALSE),
(7, 'Johnny Depp', FALSE),
(8, 'Avatar', FALSE),
(8, 'Avengers: Endgame', TRUE),
(8, 'Titanic', FALSE),
(8, 'Star Wars: The Force Awakens', FALSE),
(9, 'H2O', TRUE),
(9, 'CO2', FALSE),
(9, 'NaCl', FALSE),
(9, 'O2', FALSE),
(10, 'Mitochondria', TRUE),
(10, 'Nucleus', FALSE),
(10, 'Ribosome', FALSE),
(10, 'Endoplasmic Reticulum', FALSE),
(11, '299,792,458 m/s', TRUE),
(11, '150,000,000 m/s', FALSE),
(11, '300,000,000 m/s', FALSE),
(11, '200,000,000 m/s', FALSE),
(12, '6', FALSE),
(12, '8', TRUE),
(12, '10', FALSE),
(12, '12', FALSE),
(13, 'The Rolling Stones', FALSE),
(13, 'Queen', TRUE),
(13, 'The Beatles', FALSE),
(13, 'Led Zeppelin', FALSE),
(14, 'Prince', FALSE),
(14, 'Michael Jackson', TRUE),
(14, 'Madonna', FALSE),
(14, 'Whitney Houston', FALSE),
(15, '1989', TRUE),
(15, '1990', FALSE),
(15, '1988', FALSE),
(15, '1991', FALSE),
(16, 'Elvis Presley', FALSE),
(16, 'Michael Jackson', TRUE),
(16, 'Prince', FALSE),
(16, 'David Bowie', FALSE),
(17, '1914', TRUE),
(17, '1918', FALSE),
(17, '1939', FALSE),
(17, '1945', FALSE),
(18, 'George Washington', TRUE),
(18, 'Thomas Jefferson', FALSE),
(18, 'John Adams', FALSE),
(18, 'Benjamin Franklin', FALSE),
(19, 'Egyptians', TRUE),
(19, 'Romans', FALSE),
(19, 'Greeks', FALSE),
(19, 'Mayans', FALSE),
(20, 'Titanic', TRUE),
(20, 'Lusitania', FALSE),
(20, 'Britannic', FALSE),
(20, 'Olympic', FALSE),
(21, 'Charles Dickens', FALSE),
(21, 'William Shakespeare', TRUE),
(21, 'Jane Austen', FALSE),
(21, 'Emily Bronte', FALSE),
(22, 'Leonardo da Vinci', FALSE),
(22, 'Vincent van Gogh', TRUE),
(22, 'Claude Monet', FALSE),
(22, 'Pablo Picasso', FALSE),
(23, 'David', FALSE),
(23, 'The Thinker', FALSE),
(23, 'Statue of Liberty', FALSE),
(23, 'David', TRUE),
(24, 'Claude Monet', TRUE),
(24, 'Vincent van Gogh', FALSE),
(24, 'Edgar Degas', FALSE),
(24, 'Paul Cezanne', FALSE),
(25, 'Pittsburgh Steelers', FALSE),
(25, 'Pittsburgh Steelers', FALSE),
(25, 'New England Patriots', TRUE),
(25, 'Dallas Cowboys', FALSE),
(26, 'Michael Phelps', TRUE),
(26, 'Usain Bolt', FALSE),
(26, 'Simone Biles', FALSE),
(26, 'Roger Federer', FALSE),
(27, 'France', TRUE),
(27, 'Germany', FALSE),
(27, 'Brazil', FALSE),
(27, 'Italy', FALSE),
(28, 'Michael Jordan', TRUE),
(28, 'LeBron James', FALSE),
(28, 'Kobe Bryant', FALSE),
(28, 'Magic Johnson', FALSE),
(29, '22', FALSE),
(29, '4', TRUE),
(29, '2+2', FALSE),
(29, 'Error', FALSE),
(30, 'Hyper Text Markup Language', TRUE),
(30, 'Home Tool Markup Language', FALSE),
(30, 'Hyperlinks and Text Markup Language', FALSE),
(30, 'Highly Textual Machine Language', FALSE),
(31, 'A type of data structure', FALSE),
(31, 'A sequence of instructions that repeats until a condition is met', TRUE),
(31, 'A method for storing data', FALSE),
(31, 'A way to organize files', FALSE),
(32, 'Lists are mutable, tuples are immutable', TRUE),
(32, 'Lists are immutable, tuples are mutable', FALSE),
(32, 'Lists and tuples are the same', FALSE),
(32, 'Lists can only store integers', FALSE),
(33, 'North America', FALSE),
(33, 'Asia', TRUE),
(33, 'Africa', FALSE),
(33, 'Europe', FALSE),
(34, 'Amazon River', FALSE),
(34, 'Nile River', TRUE),
(34, 'Yangtze River', FALSE),
(34, 'Mississippi River', FALSE),
(35, 'China', FALSE),
(35, 'Japan', TRUE),
(35, 'South Korea', FALSE),
(35, 'Thailand', FALSE),
(36, 'Sydney', FALSE),
(36, 'Canberra', TRUE),
(36, 'Melbourne', FALSE),
(36, 'Brisbane', FALSE),
(37, 'Tomatoes', FALSE),
(37, 'Avocado', TRUE),
(37, 'Onions', FALSE),
(37, 'Peppers', FALSE),
(38, 'Greece', FALSE),
(38, 'Italy', TRUE),
(38, 'Spain', FALSE),
(38, 'France', FALSE),
(39, 'Sushi', TRUE),
(39, 'Ramen', FALSE),
(39, 'Tempura', FALSE),
(39, 'Udon', FALSE),
(40, 'Paprika', FALSE),
(40, 'Turmeric', TRUE),
(40, 'Cumin', FALSE),
(40, 'Ginger', FALSE),
(41, 'Pac-Man', FALSE),
(41, 'Mario', TRUE),
(41, 'Sonic the Hedgehog', FALSE),
(41, 'Donkey Kong', FALSE),
(42, 'Link', TRUE),
(42, 'Zelda', FALSE),
(42, 'Ganondorf', FALSE),
(42, 'Impa', FALSE),
(43, 'Tetris', FALSE),
(43, 'Minecraft', TRUE),
(43, 'Grand Theft Auto V', FALSE),
(43, 'Wii Sports', FALSE),
(44, 'Fortnite', FALSE),
(44, 'Minecraft', TRUE),
(44, 'Call of Duty', FALSE),
(44, 'League of Legends', FALSE),
(45, 'Poseidon', TRUE),
(45, 'Zeus', FALSE),
(45, 'Hades', FALSE),
(45, 'Ares', FALSE),
(46, 'Thor', TRUE),
(46, 'Odin', FALSE),
(46, 'Loki', FALSE),
(46, 'Freya', FALSE),
(47, 'Mars', TRUE),
(47, 'Jupiter', FALSE),
(47, 'Neptune', FALSE),
(47, 'Saturn', FALSE),
(48, 'Sphinx', FALSE),
(48, 'Griffin', TRUE),
(48, 'Centaur', FALSE),
(48, 'Minotaur', FALSE),
(49, 'Lion', TRUE),
(49, 'Tiger', FALSE),
(49, 'Elephant', FALSE),
(49, 'Giraffe', FALSE),
(50, 'Blue Whale', TRUE),
(50, 'African Elephant', FALSE),
(50, 'Giraffe', FALSE),
(50, 'Hippopotamus', FALSE),
(51, 'Parrot', TRUE),
(51, 'Eagle', FALSE),
(51, 'Penguin', FALSE),
(51, 'Ostrich', FALSE),
(52, 'Cheetah', TRUE),
(52, 'Lion', FALSE),
(52, 'Gazelle', FALSE),
(52, 'Horse', FALSE),
(53, 'Neil Armstrong', TRUE),
(53, 'Buzz Aldrin', FALSE),
(53, 'Yuri Gagarin', FALSE),
(53, 'Alan Shepard', FALSE),
(54, 'Jupiter', TRUE),
(54, 'Saturn', FALSE),
(54, 'Uranus', FALSE),
(54, 'Neptune', FALSE),
(55, 'Saturn', TRUE),
(55, 'Jupiter', FALSE),
(55, 'Uranus', FALSE),
(55, 'Neptune', FALSE),
(56, 'Milky Way', TRUE),
(56, 'Andromeda', FALSE),
(56, 'Triangulum', FALSE),
(56, 'Whirlpool', FALSE),
(57, 'William Shakespeare', TRUE),
(57, 'Jane Austen', FALSE),
(57, 'Charles Dickens', FALSE),
(57, 'Emily Bronte', FALSE),
(58, 'Martin Luther King Jr.', TRUE),
(58, 'Abraham Lincoln', FALSE),
(58, 'John F. Kennedy', FALSE),
(58, 'Nelson Mandela', FALSE),
(59, 'Franklin D. Roosevelt', TRUE),
(59, 'Theodore Roosevelt', FALSE),
(59, 'Woodrow Wilson', FALSE),
(59, 'Herbert Hoover', FALSE),
(60, 'John F. Kennedy', TRUE),
(60, 'Ronald Reagan', FALSE),
(60, 'Barack Obama', FALSE),
(60, 'Donald Trump', FALSE),
(61, 'Scarf', TRUE),
(61, 'Tie', FALSE),
(61, 'Bow tie', FALSE),
(61, 'Cravat', FALSE),
(62, 'Coco Chanel', TRUE),
(62, 'Christian Dior', FALSE),
(62, 'Yves Saint Laurent', FALSE),
(62, 'Giorgio Armani', FALSE),
(63, 'Wool', TRUE),
(63, 'Cotton', FALSE),
(63, 'Silk', FALSE),
(63, 'Linen', FALSE),
(64, 'Heels', TRUE),
(64, 'Boots', FALSE),
(64, 'Sandals', FALSE),
(64, 'Sneakers', FALSE),
(65, 'Mercedes-Benz', TRUE),
(65, 'BMW', FALSE),
(65, 'Audi', FALSE),
(65, 'Lexus', FALSE),
(66, 'Ford Model T', TRUE),
(66, 'Volkswagen Beetle', FALSE),
(66, 'Chevrolet Corvette', FALSE),
(66, 'Toyota Corolla', FALSE),
(67, 'Convertible', TRUE),
(67, 'Sedan', FALSE),
(67, 'Hatchback', FALSE),
(67, 'SUV', FALSE),
(68, 'Ferrari', TRUE),
(68, 'Lamborghini', FALSE),
(68, 'Porsche', FALSE),
(68, 'Maserati', FALSE),
(69, 'Dunder Mifflin', TRUE),
(69, 'Staples', FALSE),
(69, 'OfficeMax', FALSE),
(69, 'Paper Source', FALSE),
(70, 'Pam Beesly', TRUE),
(70, 'Karen Filippelli', FALSE),
(70, 'Jan Levinson', FALSE),
(70, 'Holly Flax', FALSE),
(71, 'Paper Salesman', TRUE),
(71, 'Assistant Regional Manager', FALSE),
(71, 'Regional Manager', FALSE),
(71, 'Beet Farmer', TRUE),
(72, 'The Dundies', TRUE),
(72, 'The Oscars', FALSE),
(72, 'The Emmys', FALSE),
(72, 'The Golden Globes', FALSE),
(73, 'Angel Falls', TRUE),
(73, 'Niagara Falls', FALSE),
(73, 'Victoria Falls', FALSE),
(73, 'Iguazu Falls', FALSE),
(74, 'Andes', TRUE),
(74, 'Himalayas', FALSE),
(74, 'Rocky Mountains', FALSE),
(74, 'Alps', FALSE),
(75, 'Sahara Desert', TRUE),
(75, 'Gobi Desert', FALSE),
(75, 'Arabian Desert', FALSE),
(75, 'Australian Desert', FALSE),
(76, 'Mariana Trench', TRUE),
(76, 'Puerto Rico Trench', FALSE),
(76, 'Java Trench', FALSE),
(76, 'Challenger Deep', FALSE),
(77, 'Monopoly', TRUE),
(77, 'Scrabble', FALSE),
(77, 'Clue', FALSE),
(77, 'Risk', FALSE),
(78, 'Clue', TRUE),
(78, 'Monopoly', FALSE),
(78, 'Sorry!', FALSE),
(78, 'The Game of Life', FALSE),
(79, 'Risk', TRUE),
(79, 'Settlers of Catan', FALSE),
(79, 'Ticket to Ride', FALSE),
(79, 'Carcassonne', FALSE),
(80, 'Chess', TRUE),
(80, 'Checkers', FALSE),
(80, 'Backgammon', FALSE),
(80, 'Go', FALSE),
(81, 'Bob Kane', TRUE),
(81, 'Stan Lee', FALSE),
(81, 'Jack Kirby', FALSE),
(81, 'Bill Finger', FALSE),
(82, 'Clark Kent', TRUE),
(82, 'Bruce Wayne', FALSE),
(82, 'Peter Parker', FALSE),
(82, 'Tony Stark', FALSE),
(83, 'Marvel Comics', TRUE),
(83, 'DC Comics', FALSE),
(83, 'Image Comics', FALSE),
(83, 'Dark Horse Comics', FALSE),
(84, 'Rorschach', TRUE),
(84, 'The Joker', FALSE),
(84, 'Lex Luthor', FALSE),
(84, 'Doctor Doom', FALSE),
(85, 'Rome', TRUE),
(85, 'Athens', FALSE),
(85, 'Cairo', FALSE),
(85, 'Istanbul', FALSE),
(86, 'Eiffel Tower', TRUE),
(86, 'Louvre', FALSE),
(86, 'Notre Dame Cathedral', FALSE),
(86, 'Arc de Triomphe', FALSE),
(87, 'Australia', TRUE),
(87, 'New Zealand', FALSE),
(87, 'Indonesia', FALSE),
(87, 'Philippines', FALSE),
(88, 'Machu Picchu', TRUE),
(88, 'Chichen Itza', FALSE),
(88, 'Petra', FALSE),
(88, 'Colosseum', FALSE),
(89, 'Melody', TRUE),
(89, 'Harmony', FALSE),
(89, 'Rhythm', FALSE),
(89, 'Tempo', FALSE),
(90, 'Tempo', TRUE),
(90, 'Pitch', FALSE),
(90, 'Dynamics', FALSE),
(90, 'Timbre', FALSE),
(91, 'Dynamics', TRUE),
(91, 'Pitch', FALSE),
(91, 'Tempo', FALSE),
(91, 'Rhythm', FALSE),
(92, 'Sharp', TRUE),
(92, 'Flat', FALSE),
(92, 'Natural', FALSE),
(92, 'Accent', FALSE),
(93, 'Jane Austen', TRUE),
(93, 'Charlotte Bronte', FALSE),
(93, 'Emily Bronte', FALSE),
(93, 'Virginia Woolf', FALSE),
(94, 'Scout Finch', TRUE),
(94, 'Atticus Finch', FALSE),
(94, 'Jem Finch', FALSE),
(94, 'Boo Radley', FALSE),
(95, 'A Streetcar Named Desire', TRUE),
(95, 'The Glass Menagerie', FALSE),
(95, 'Cat on a Hot Tin Roof', FALSE),
(95, 'The Night of the Iguana', FALSE),
(96, 'F. Scott Fitzgerald', TRUE),
(96, 'Ernest Hemingway', FALSE),
(96, 'William Faulkner', FALSE),
(96, 'John Steinbeck', FALSE),
(97, '3.14159', TRUE),
(97, '3.14', FALSE),
(97, '3.1416', FALSE),
(97, '3.142', FALSE),
(98, '12', TRUE),
(98, '10', FALSE),
(98, '14', FALSE),
(98, '16', FALSE),
(99, '2', TRUE),
(99, '3', FALSE),
(99, '4', FALSE),
(99, '5', FALSE),
(100, '32', TRUE),
(100, '24', FALSE),
(100, '64', FALSE),
(100, '48', FALSE);
